services:
  php-fpm:
    build: docker/php-fpm
    container_name: ${COMPOSE_PROJECT_NAME:-race-results}.php-fpm
    volumes:
      - ./:/usr/local/src/
      - ./docker/php-fpm/php.ini-${APP_ENV:-development}:/usr/local/etc/php/php.ini
  nginx:
    image: nginx:1.23.2-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-race-results}.nginx
    depends_on:
      - php-fpm
    ports:
      - 8000:80
    volumes:
      - ./:/usr/local/src/
      - ./docker/nginx/:/etc/nginx/conf.d/
